name: Pull request triggers for workflow

run-name: Workflow for testing event based triggers in Github Actions
on:
 pull_request:
  branches:
  - master
jobs:
 Echo-build:
  runs-on: ubuntu-latest
  steps:
    - name: First step
      run: echo "First Workflow"
