name: Test triggers for workflow

run-name: Workflow for testing event based triggers in Github Actions
on:
 issues:
  types:
  - opened
  - labeled
  label:
    types:
      - created
jobs:
 Echo-build:
  runs-on: ubuntu-latest
  steps:
    - name: First step
      run: echo "First Workflow"
